# Generated by Django 6.0.1 on 2026-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_ahcpreprosesing_kmeanspreprosesing'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq')], default='gemini', max_length=20),
        ),
    ]
